version: "3.9"

services:
  postgres:
    container_name: blomup_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${pg_database}
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
    ports:
      - "${pg_port}:5432"
    networks:
      - blomup_net

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${pg_user}:${pg_password}@${pg_host}:${pg_port}/${pg_database}
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}
      firebase_credentials_path: ${firebase_credentials_path}
    ports:
      - "80:8000"
      - "433:8000"
    depends_on:
      - postgres
    networks:
      - blomup_net

networks:
  blomup_net:
    driver: bridge
